# /docker-compose.yml
version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    container_name: dashboard-app
    image: dashboard-app
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app/src
    ports:
      - 3000:3000
    depends_on:
      - backend
